# Generated by Django 4.1.5 on 2023-01-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0002_alter_note_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='note',
            new_name='notepad',
        ),
    ]
