# Generated by Django 4.1.5 on 2023-02-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notepad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.TextField(max_length=30)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
